# Generated by Django 3.1 on 2020-09-08 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('barcode', models.IntegerField(primary_key=True, serialize=False)),
                ('stuff_name', models.CharField(max_length=35)),
                ('stuff_category', models.CharField(max_length=35)),
                ('nutriscore', models.CharField(max_length=5)),
                ('favourites', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
