# Generated by Django 3.1 on 2020-09-15 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('barcode', models.BigIntegerField(primary_key=True, serialize=False)),
                ('image', models.URLField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=100)),
                ('nutriscore', models.CharField(max_length=5)),
                ('favourites', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
