# Generated by Django 3.1 on 2020-09-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20200913_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='barcode',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
