# Generated by Django 3.1 on 2020-09-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20200915_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
